input {
  tcp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  if [type] == "investtrack" {
    mutate {
      add_field => { "app" => "investtrack" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "investtrack-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
